### ISSUE TITLE
Correção Exercício WhatsApp Lite

### ISSUE THREAD

**Issue by mathiasgheno** [Tallyee/WhatsApLight#1]
# Enunciado

Considere o enunciado [disponível aqui](https://www.notion.so/Aula-09-1-de-Novembro-141dd67f427e4f47984134d6d1a24571?pvs=4#ae5328e129be448cb76ce90ae2b04f55).

# Correção

O principal problema do seu código está na falta do uso do `position: absolute` e `position: relative` que deveria ser usado em conjunto com a classe que representam uma mensagem, como o `um`. O `absolute` deveria ficar no botão (no seu caso um `svg`), assim vc poderia controlar a disposição do elemento. 

```css
.um {
    width: fit-content;
    padding: 10px 25px;
    position: relative;
}
.um svg {
    position: absolute;
    bottom: 5px;
    right: 5px;
}
```

Além disso, faltou fazer a disposição das mensagens. As mensagens que ficam a direita e as que ficam as esquerda, suas mensagens estão ocupando toda a largura. 

Nota: 5

# Comentários

Não perca o hábito de formatar o seu código. Você pode fazer isso através do comando "> format document" do VS Code.
